### ISSUE TITLE
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_EMPTY

### ISSUE THREAD

**Issue by trendingnow1** [igorwojda/android-showcase#117]
I clone the repo and try to run it then it shows 

`Installation did not succeed.`
`The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_EMPTY`
`List of apks:`
`[0] 'D:\AndroidStudioProjects\SampleKotlinBase\android-showcase\app\build\outputs\apk\debug\app-debug.apk'`
`[1] 'D:\AndroidStudioProjects\SampleKotlinBase\android-showcase\feature_album\build\outputs\apk\debug\feature_album-debug.apk'`
`[2] 'D:\AndroidStudioProjects\SampleKotlinBase\android-showcase\feature_favourite\build\outputs\apk\debug\feature_favourite-debug.apk'`
`[3] 'D:\AndroidStudioProjects\SampleKotlinBase\android-showcase\feature_profile\build\outputs\apk\debug\feature_profile-debug.apk'`
`Installation failed due to: 'null'`

may be I miss something.
Android Studio 4.

**Comment by igorwojda** [comment]
Hard o say, but this can be dependent on he version of the Android Studio. 
Can you try clean checkout and run the project on AS 4.2 Beta 4 (or newer?)

**Comment by igorwojda** [comment]
I had a similar issue once when the app was already installed on the device - I had to manually uninstall it before installing/running from AS.

Besides this, I can't really reproduce this nowadays, so I will close this for now.
