### ISSUE TITLE
Unexpected end of stream

### ISSUE THREAD

**Issue by hram** [igorwojda/android-showcase#121]
> I/okhttp.OkHttpClient: --> POST http://ws.audioscrobbler.com/2.0/?method=album.search&album=sd&limit=60&api_key=70696db59158cb100370ad30a7a705c1&format=json
> I/okhttp.OkHttpClient: Content-Length: 0
> I/okhttp.OkHttpClient: User-Agent: showcase/1.0 Dalvik/2.1.0 (Linux; U; Android 10; Android SDK built for x86 Build/QSR1.200715.002)
> I/okhttp.OkHttpClient: --> END POST (0-byte body)
> I/okhttp.OkHttpClient: <-- HTTP FAILED: java.io.IOException: unexpected end of stream on http://ws.audioscrobbler.com/...
> 

Actualy charles logs shows that response is OK
![изображение](https://user-images.githubusercontent.com/2150637/95659546-7d151e00-0b2a-11eb-9971-4b9b9b6b269d.png)

**Comment by igorwojda** [comment]
I have updated multiple libraries, including Retofit and OKHttp and I don't see the error nodadays.
Can you still reproduce this error?

**Comment by igorwojda** [comment]
I will lose this for now.

**Comment by hram** [comment]
@igorwojda Hi
Today I was update project and error is present.
Error is fixed if change HTTP method form POST to GET on request searchAlbumAsync
`@GET("./?method=album.search")`

**Comment by hram** [comment]
the same behavior for getAlbumInfoAsync
`@GET("./?method=album.getInfo")`
