### ISSUE TITLE
use the jetpack compose 

### ISSUE THREAD

**Issue by mahramane** [igorwojda/android-showcase#154]
...

**Comment by igorwojda** [comment]
Currently most of the dependencies are in alpha state (`1.0.0-alpha12`) and AS `ARCTIC FOX (2020.3.1) CANARY 7` is recommended. 

I will take a look at this after JetPack compose will hit more mature version.

**Comment by igorwojda** [comment]
Since JetPack Compose is stable nowadays it will be added to the project soon.
