### ISSUE TITLE
Navigation stopped working

### ISSUE THREAD

**Issue by 4ehonte** [igorwojda/android-showcase#155]
Seems that the navigation stopped working after https://github.com/igorwojda/android-showcase/pull/153. 
Nothing happens when I click on an album because this check never returns true:
https://github.com/igorwojda/android-showcase/blob/1f4b5d8c5f3fdee02e0bdf7f0dff9db77a65357a/app/src/main/kotlin/com/igorwojda/showcase/app/presentation/NavHostActivity.kt#L57-L59

If I'm not mistaken, `currentFragment?.id` returns the id of the fragment's container. It's not the same as `currentDestination.id`, which is specified in navigation graph xml.

**Comment by igorwojda** [comment]
Album is the default view (the one you see after launching the app), so nothing should actually hapend. 

BTW Before this fix was implemented clicking on the `Albums` would recreate the whole fragment.

**Comment by 4ehonte** [comment]
I mean, nothing happens even when I click on one of the cards, album details won't open. Or is it a problem with my build only?

**Comment by enesfurkangenc** [comment]
I'm living the same mistake. I click album card but can't never navigate detail fragment

**Comment by igorwojda** [comment]
This bug was introduced by prev navigation "fix". This PR solves this issue https://github.com/igorwojda/android-showcase/pull/156

**Comment by enesfurkangenc** [comment]
@igorwojda I have a again problem. I wanna navigate feature_auth to feature_feed. But crash app.

`Navigation action/destination com.igorwojda.showcase:id/action_featureAuthNavGraph_to_featureFeedNavGraph cannot be found from the current destination Destination(com.igorwojda.showcase.feature_auth:id/loginFragment) label=LoginFragment class= com.igorwojda.showcase.feature.auth.presentation.login.LoginFragment`

**Comment by enesfurkangenc** [comment]
@igorwojda I fixed it this way;

app_nav_graph.xml

     <action
        android:id="@id/featureFeedNavGraph"
        app:destination="@id/featureFeedNavGraph" />


    <include-dynamic
        android:id="@+id/featureAuthNavGraph"
        app:graphResName="feature_auth_nav_graph"
        app:moduleName="feature_auth">

        <action
            android:id="@+id/featureFeedNavGraph"
            app:destination="@id/featureFeedNavGraph" />

    </include-dynamic>
