### ISSUE TITLE
How to allocate splash screen activity under clean architecture?

### ISSUE THREAD

**Issue by enesfurkangenc** [igorwojda/android-showcase#159]
I just wonder when I have a login activity in my App, I should place the splash activity inside the APP module or separately has a module with presentation/domain/data for splash process? Thanks a lot.

**Comment by Timothybas** [comment]
@enesfurkangenc Did you find any solution? Me too running in the same situation

**Comment by Timothybas** [comment]
I created a dynamic module called **feature_auth** and included it in the APP module and in NavHostActivity I have added **addOnDestinationChangedListener** to hide show **BottomNavigationView** Is that correct?

**Comment by igorwojda** [comment]
There are no answers set in stone here.  The `feature_auth` approach sounds good.
I will take a note from this issue and try to extends app functionality.
