### ISSUE TITLE
how to navigate from featureA to featureB without BottomNavController?

### ISSUE THREAD

**Issue by audiserg** [igorwojda/android-showcase#162]
1.how to navigate from featureA to start of featureB without BottomNavController?
    if i try navigate from graphFeatureA to graphFeatureB as action, i got a "destination not found exception"
2. how to navigate from featureA to featureB any Fragment?
3. Can i use safeargs in both scenario?

**Comment by igorwojda** [comment]
The project is being upgraded to version 2.0 (WiP).
I am closing this issue as it is most likely obsolete (2.0 does not support dynamic feature modules due to issues with ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM).
