### ISSUE TITLE
Deduplication in BaseViewModel

### ISSUE THREAD

**Issue by bitvale** [igorwojda/android-showcase#164]
https://github.com/igorwojda/android-showcase/blob/3f30d3333f06288adc6f3a1b31198fbd50b1c3aa/app/src/main/kotlin/com/igorwojda/showcase/base/presentation/viewmodel/BaseViewModel.kt#L24

Is this comment correct? 

I think `Delegates.observable` do nothing with deduplication. Per documentation:

![image](https://user-images.githubusercontent.com/14936809/118393713-c4bfd300-b640-11eb-8bbd-70b59f0df0d0.png)

And implementation:

![image](https://user-images.githubusercontent.com/14936809/118393744-eb7e0980-b640-11eb-8efa-29a1b01739d5.png)

It just calls the callback after setting the new value (the new value could be the same).

**Comment by igorwojda** [comment]
Good point @bitvale.

Update the code thx
