### ISSUE TITLE
 third-party package

### ISSUE THREAD

**Issue by m-phanat** [igorwojda/android-showcase#195]
Let's say I have a third-party package. Will I be able to use FeatureManager and FeatureKodeinModule? If so, how?
Thank you.

**Comment by igorwojda** [comment]
I don;t understad t hquesiton. Can you please elaborate?

BTW The project is being upgraded to version 2.0 (WPi)

**Comment by igorwojda** [comment]
I am closing it for now. Feel free to reopen if you want to discuss it any further
