### ISSUE TITLE
How about performance if state alway update whole view?

### ISSUE THREAD

**Issue by hoangthan** [igorwojda/android-showcase#196]
Hi. I'm wondering about the pattern you are using with State.
Anytime state is changed from ViewModel Fragment/Activity should be triggered observed function. It gonna update whole view, state, recyclerview,... Do you have any idea to deal with that ?

**Comment by igorwojda** [comment]
The project has been upgraded to version 2.0.
I will be migrating UI to Jetpack Compose and this should provide a better UI update mechanism (performance wise).
