### ISSUE TITLE
More info about every element of project

### ISSUE THREAD

**Issue by warcayac** [igorwojda/android-showcase#240]
Hi, 

I'm new with Clean Architecture so I'm learning about it, I've read some articles and they are generally either lacking about understandable information or about how to properly implement their theory into a real project. I've noted everyone has their own interpretation, specially with **features** because for some people it is about pages/screens of app whereas for other is something else.

I've read your articles _"Multiple ways of defining Clean Architecture layers"_ and _"Android Showcase 2.0"_, and they have more sense for me and are more balanced between theory and a real implementation, so I decided to port (translate) your Kotlin project into a Flutter project, but I'm having some trouble understanding your code because I don't know Kotlin, I'm learning on the fly and it's hard. For example this code:

**Result.kt**
```
sealed interface Result<out T> {
    data class Success<T>(val value: T) : Result<T>
    data class Failure(val throwable: Throwable? = null) : Result<Nothing>
}
```
**ResultExt.kt**
```
sealed interface Result<out T> {
    data class Success<T>(val value: T) : Result<T>
    data class Failure(val throwable: Throwable? = null) : Result<Nothing>
}
```
What is it that they do? how should they be used? So to port your code into another language I need documentation for every element (class, interface, function) of your project. 

Is it possible to provide this info, please?

**Comment by igorwojda** [comment]
I agree that CA is a bit abstract.

It is impossible to document everything, especially if you are asking about Kotlin-related stuff that is covered by Korlin docs (not really the goal of this project), however, I will try to share some light.

Conceptually `sealed interface Result` is just a common interface to these two classes representing network response states - `Success` (containing data/value) and `Failure ` (containing the error). The `mapSuccess` extension in `ResultExt.kt` perform an action only if the Result is of type Success.

I suggest reading about 
- Kotlin Sealed interfaces
- Kotlin data classes
- Kotlin extension function

BTW translating programs from one language to another is a great way to learn

**Comment by warcayac** [comment]
> BTW translating programs from one language to another is a great way to learn

Yeah, you're right, thanks.
