### ISSUE TITLE
Fuel for network

### ISSUE THREAD

**Issue by matteocrippa** [igorwojda/android-showcase#25]
Just an idea, to consider [Fuel](https://github.com/kittinunf/fuel) as an alternative to Retrofit using in particular the [routing](https://github.com/kittinunf/fuel/blob/master/fuel/README.md#routing-support) feature that allow you to easily have a nice API (quite reusable on iOS with Alamofire too)

**Comment by igorwojda** [comment]
Thx for the suggestion.

I have initially used Fuel when I created this repo a few months ago. In the beginning, it worked fine, but I quickly encountered some problems. THB I don't remember the exact issue, but looking at my commits and my Fuel reported issues I think I had some issues with nullable data models.

I believe that my original issue was that sometimes API would return empty data or different data model for success and error responses (eg. when Album is not found). Having no control over external API and being unable to easily parse the data I switched to old and concrete `Retrofit`.

Thats being said it was over nice months ago (Fuel was still at version `1.x`), so maybe nowadays some of these issues are resolved...

Anyway, I wonder what would be the reason for you @matteocrippa to switch to `Fuel` nowadays?

**Comment by matteocrippa** [comment]
I liked Fuel as approach and was a contributor for the specific API/routing part of the code, so yep I was a bit involved and being an iOS developer too for me was very interesting to have a code that basically you can easily port to Swift with few lines of code.

Retrofit personally I don't like the syntax, for me is more Java like, but for sure is much more stable

**Comment by igorwojda** [comment]
No promises, but I may give `Fuel` a try at some point.

**Comment by igorwojda** [comment]
I will stick with Retrofit for now, because it is most used networking library for Android project nowadays.
