### ISSUE TITLE
Could you add a pure Kotlin module?

### ISSUE THREAD

**Issue by trietbui85** [igorwojda/android-showcase#286]
It's quite popular to have pure Kotlin module in the app. Could you add such module to demonstrate how to config it?

**Comment by igorwojda** [comment]
Pure Kotlin is outside of the scope of this project. This would fit better for multiplatform project or alternative [module per layer approach](https://proandroiddev.com/multiple-ways-of-defining-clean-architecture-layers-bbb70afa5d4a) (not this project).
