### ISSUE TITLE
Help on how to add a new module

### ISSUE THREAD

**Issue by clevertrevor** [igorwojda/android-showcase#48]
I think this project is great as a showcase. However, I am having difficulty adding a module. I tried copy/pasting/refactoring an existing module and I also tried the various options under: File > New >New Module. Can you explain how to add a new module or add it to the README? Also, I am willing to contribute this knowledge to the README if I could figure it out.

**Comment by igorwojda** [comment]
Gradle Kotlin DSL is not 100% supported by AS - when you use module creators some redundant files are added, so we have to remove them (this is the only issue I have currently).

Assuming you want to add `onboarding` feature.

**Add module in AS**

1. Create a new module in AS
![image](https://user-images.githubusercontent.com/530122/64278738-5a86fd80-cf45-11e9-9231-1217eafac431.png)

2. Select module type (Usually `Dynamic Feature Module` or `Android Library`)
![image](https://user-images.githubusercontent.com/530122/64278758-65419280-cf45-11e9-8195-db649e1d3e04.png)

3. Configure module (set feature name and add `.feature` sub-package in the package name)
![image](https://user-images.githubusercontent.com/530122/64279080-31b33800-cf46-11e9-840f-8ab9c1bb8c81.png)

4. Configure on-demand (currently it is not set up, so go with `include module at install time`)
![image](https://user-images.githubusercontent.com/530122/64279256-8787e000-cf46-11e9-8d6c-00dc76853ea8.png)

**Configure Gradle**
1. Delete `settings.gradle` file (we already have `settings.gradle.kts`)
2. Delete `feature_onboarding\build.gradle` (we will be using `build.gradle.kts` instead)
2. Delete `app\build.gradle` 
3. Copy module configuration from another module eg. copy `feature_favourite\build.gradle.kts` to `feature_onboarding\build.gradle.kts`
4. Add module to Gradle by modifying `buildSrc\src\kotlin\ModuleDependency\`

```
object ModuleDependency {
    // All consts are accessed via reflection
    const val APP = ":app"
    const val FEATURE_ALBUM = ":feature_album"
    const val FEATURE_PROFILE = ":feature_profile"
    const val FEATURE_FAVOURITE = ":feature_favourite"
    const val FEATURE_ONBOARDING = ":feature_onboarding"
    // ..
```

(above const will be retrieved by `settings.gradle.kts` that defines list of modules/subproject for Gradle build)

**Final thoughts**
This is a bit more work to add a single module. Overtime AS will stop adding these redundant files, but for now, we could script this process using bash or [kscript](https://github.com/holgerbrandl/kscript) and we could have Gradle tasks like this:

`./gradlew add-dynamic-feature onboarding`
or
`./gradlew add-android-library onboarding`

**Comment by clevertrevor** [comment]
I really appreciate all the steps and screenshots you added @igorwojda . I'm much farther along and my commit looks the exact same, however AS is still not recognizing my new module `feature_news`. I can build and run the app successfully. When I looked at Load/Unload modules, `feature_news` isn't in the list. Do you know what the issue might be? 
<img width="166" alt="Screen Shot 2019-09-04 at 4 41 51 PM" src="https://user-images.githubusercontent.com/1302413/64300840-4cc87c80-cf33-11e9-8958-2074c521a2d9.png">

**Comment by igorwojda** [comment]
I have committed all my changes - check this branh `new-feature-example` and here is the commit 
https://github.com/igorwojda/android-showcase/commit/990d05f4bcbb789e265a624f7ed79db1aea1ae87

BTW Make sure you have AS 3.5 installed

**Comment by clevertrevor** [comment]
I checked out your branch and had to make some more changes to get the project to run. I had to undo step 5 because `com.igorwojda.feature.onboarding.AndroidManifest` required it for `dist:title`. At this point, the app will build succesfully and crash when run with the below error.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.igorwojda.showcase, PID: 7468
    java.lang.ExceptionInInitializerError
        at com.igorwojda.showcase.app.ShowcaseApplication$kodein$1.invoke(ShowcaseApplication.kt:23)
        at com.igorwojda.showcase.app.ShowcaseApplication$kodein$1.invoke(ShowcaseApplication.kt:19)
        at org.kodein.di.internal.KodeinImpl$Companion.newBuilder(KodeinImpl.kt:22)
        at org.kodein.di.internal.KodeinImpl$Companion.access$newBuilder(KodeinImpl.kt:21)
        at org.kodein.di.internal.KodeinImpl.<init>(KodeinImpl.kt:19)
...
     Caused by: java.lang.ClassNotFoundException: Kodein module class not found com.igorwojda.showcase.feature.onboarding.FeatureKodeinModule
        at com.igorwojda.showcase.app.feature.FeatureManager.<clinit>(FeatureManager.kt:19)
        	... 64 more
```

I was able to fix the error by copying/refactoring `FeatureKodeinModule.kt` from the `feature_album` module.
```
package com.igorwojda.showcase.feature.onboarding

import com.igorwojda.showcase.app.feature.KodeinModuleProvider

import org.kodein.di.Kodein

internal const val FEATURE_NAME = "Onboarding"

object FeatureKodeinModule : KodeinModuleProvider {

    override val kodeinModule = Kodein.Module("${FEATURE_NAME}Module") {

    }
}
```
Now, the project runs successfully!
