### ISSUE TITLE
Purpose of NavHostActivity

### ISSUE THREAD

**Issue by narko** [igorwojda/android-showcase#50]
Hi, would you help me understanding the purpose of the following line? I am quite new to NAC and I don't really understand the goal of NavHostActivity.
Thanks!

https://github.com/igorwojda/android-showcase/blob/29ac9262958a63939b6ec7a101dace7c68969104/app/src/main/res/layout/activity_nav_host.xml#L8

**Comment by igorwojda** [comment]
thx for the answer @clevertrevor.
I think we can close the issue.
