### ISSUE TITLE
App crashes when you click on two albums at the same time

### ISSUE THREAD

**Issue by palicka** [igorwojda/android-showcase#54]
App crashes when you click on two albums at the same time

**Comment by yshinkarev** [comment]
Disable network, start app, crashed too.

**Comment by igorwojda** [comment]
Offline app launch crash is fixed, so I will rename this ticket to deal with the crashes when you click on two albums at the same time

**Comment by igorwojda** [comment]
This is correctly fixe by this PR https://github.com/igorwojda/android-showcase/pull/156
