### ISSUE TITLE
模块配置不生效，无法运行是怎么回事？

### ISSUE THREAD

**Issue by zanezha0** [igorwojda/android-showcase#59]
![image](https://user-images.githubusercontent.com/21376780/65844375-9c4e6c80-e368-11e9-8f78-ff5db5e3c394.png)

**Comment by igorwojda** [comment]
1. Make sure you have the newest AS 3.5 and pull a clean version of the project from the repo.

2. This should work, but sometimes AS restart may be needed after opening the project). 

3. Try to run `Sync project with Gradle` AS action
![image](https://user-images.githubusercontent.com/530122/65912328-edd91480-e3c5-11e9-8fa2-59676691b840.png)

**Comment by madreain** [comment]
https://github.com/madreain/AACHulk 看看这个怎么样

**Comment by igorwojda** [comment]
It's an old issue, so I will close it for now.
Feel free to reopen it if problem still exists.
