### ISSUE TITLE
Duplicate plugin id's?

### ISSUE THREAD

**Issue by IgorGanapolsky** [igorwojda/android-showcase#60]
Hello,
thank you for this repo.  Why do you have duplicate plugin id's?  Specifically in **settings.gradle.kts** and in **build.gradle.kts**:
`plugins {
        id(GradlePluginId.DETEKT) version GradlePluginVersion.DETEKT`

**Comment by igorwojda** [comment]
I think this issue is not present any more, so I will close it. Feel free to reopen this iff needed.
