### ISSUE TITLE
Dynamic feature modules and navigation component work together

### ISSUE THREAD

**Issue by aojiaoqiang** [igorwojda/android-showcase#61]
Hello,
thank you for this repo.I would like to ask, when working together with Dynamic Feature modules and Navigation components, I directly configured the Fragment path of Dynamic Feature module in the Navigation. However, when I was running the project, the system told me that I could not find the target.I noticed that your project is also written in the same way, but the runtime is normal. May I ask if it is my configuration error?Now I have changed the configuration consistent with yours, but it still cannot solve this problem. If you have time trouble, you can help me, thank you!

**Comment by igorwojda** [comment]
Hey this is quite old issue, so I will close it, because navigation setup has changed over time.
