### ISSUE TITLE
Cannot run module

### ISSUE THREAD

**Issue by abalta** [igorwojda/android-showcase#64]
Hi, I have cloned your repo and wait for build. Everything was ok. But, I don't see any configuration to run. I have also try gradle sync, inv. cache and restart but nothing works.

Android studio version is: 3.5.3

**Comment by aryayudha** [comment]
Hi, maybe you can try this 

https://stackoverflow.com/questions/46791306/syncfailed-errorcause-org-jetbrains-plugins-gradle-tooling-modelbuilderservice

**Comment by abalta** [comment]
Thanks I've already built.
