### ISSUE TITLE
Espresso Tests with Dynamic Feature Modules

### ISSUE THREAD

**Issue by Gabrix94** [igorwojda/android-showcase#69]
Hi @igorwojda you're project is probably the most complete sample around!
Do you plan to add android UI tests?
I'm currently finding difficulties testing the UI with dynamic Feature Modules(with espresso) and was hoping to find something to reference.
Thanks,
Gabriele.

**Comment by igorwojda** [comment]
Thx @Gabrix94. Glad that you like it. 

UI tests are someware on my backlog, but TBH it will take me a while to add them as I have different priorities. Feel free to open PR and help mee a bit when you figure this out :-)

**Comment by igorwojda** [comment]
I will close this one as dynamic-feature modules have been removed for now.
