### ISSUE TITLE
Demo instructions missing

### ISSUE THREAD

**Issue by tomaszrykala** [igorwojda/android-showcase#7]
A description of a demo search would be useful. The app launches with "search album" tag, but it's not clear whether it's a music or photo album. 

Having searched for `adele`, the list did not populate with any results, yet there appear items clickable, which launch a new screen with images missing. This is potentially a separate issue.

**Comment by igorwojda** [comment]
I am currently working heavily to improve main parts of the app including new material UI, better README and much more.

The first part of UI has just been merged where - the search input was replaced with the instantly loaded list of items. More will come soon...

Thanks for the feedback.

**Comment by igorwojda** [comment]
Now we have new UI and improved readme I will close this issue. 
If you have any more sugesstions please feel free to reopen it.

Thx for the feedback.
