### ISSUE TITLE
Data Flow in AlbumListFragment

### ISSUE THREAD

**Issue by chamid** [igorwojda/android-showcase#74]
Hi igor
As you explain in Data Flow section in image you show that in Album List Screen user pressed a button, then you delegate it to viewmodel

but again in the same screen you wrote: 
```
albumAdapter.setOnDebouncedClickListener {
            
    val navDirections = AlbumListFragmentDirections
        .actionAlbumListToAlbumDetail(it.artist, it.name, it.mbId)
    findNavController().navigate(navDirections)
}
```

Shouldn't it be viewmodels's responsibility? why view decide to navigate to where instead of delegating it to viewmodel and the viewmodel decide to go where by notifying view?

**Comment by igorwojda** [comment]
Hello 
Thank you for the contribution.

I have implemented better navigation flow in and introduced new class `NavigationManager`.

More details: https://github.com/igorwojda/android-showcase/pull/91.

BTW If you are interested in more contribution please take a look at one of this [issues ](https://github.com/igorwojda/android-showcase/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%E2%9C%8D%EF%B8%8Fready+to+grab%22)
