### ISSUE TITLE
Gradle: Change source set folder `java` -> `kotlin`

### ISSUE THREAD

**Issue by igorwojda** [igorwojda/android-showcase#80]
Initially I was against, but now I think that we could change source set folder from `java` to `kotlin`.
Things to consider:
- mate this change generic (apply to all modules, even future ones)
- change `main` and `test` source sets

More read:
https://handstandsam.com/2020/04/12/where-should-i-put-kotlin-code-in-an-android-project/

**Comment by jrodriguezva** [comment]
I would like to do this

**Comment by igorwojda** [comment]
Please go ahead

**Comment by igorwojda** [comment]
Closed by https://github.com/igorwojda/android-showcase/pull/119
