### ISSUE TITLE
Gradle: Duplicated `compileOptions` and `kotlinOptions` blocks

### ISSUE THREAD

**Issue by igorwojda** [igorwojda/android-showcase#81]
`compileOptions` and `kotlinOptions` block are duplicated in each module. Ideally this configuration should be applied only once (and work all the times, even for future modules).

```
compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

kotlinOptions {
    jvmTarget = JavaVersion.VERSION_1_8.toString()
}
```

**Comment by Thanatos23** [comment]
i'd like to work on this

**Comment by igorwojda** [comment]
Still want to work on that @iam-alamgir ?
