### ISSUE TITLE
Gradle:  Duplicated configuration in `android` block

### ISSUE THREAD

**Issue by igorwojda** [igorwojda/android-showcase#82]
Some elements within `android` block are duplicated in each module. Ideally this configuration should be applied only once (and work all the times, even for future modules).

```
android {
    compileSdkVersion(AndroidConfig.COMPILE_SDK_VERSION)

    defaultConfig {
        minSdkVersion(AndroidConfig.MIN_SDK_VERSION)
        targetSdkVersion(AndroidConfig.TARGET_SDK_VERSION)

        versionCode = AndroidConfig.VERSION_CODE
        versionName = AndroidConfig.VERSION_NAME
        testInstrumentationRunner = AndroidConfig.TEST_INSTRUMENTATION_RUNNER
    }
...
```

**Comment by ISatya** [comment]
I would like to do this. My approach would be to create a common gradle file with the android block and apply it in each module. As described in this [post]( https://medium.com/capital-one-tech/sharing-gradle-configuration-in-multi-module-android-projects-370602f526a7).
If you prefer any other solution then please let me know.

**Comment by Thanatos23** [comment]
i'd like to work on this.
related to #81

**Comment by igorwojda** [comment]
Go ahead @Thanatos23

**Comment by igorwojda** [comment]
Go ahead @Thanatos23

**Comment by igorwojda** [comment]
Still want to work on that @iam-alamgir ?

**Comment by iam-alamgir** [comment]
I already created a plugin that injects the dependencies into settings.gradle. Currently working on auto generation of related files in buildSrc.

**Comment by igorwojda** [comment]
Implemented by using Gradle local plugins https://github.com/igorwojda/android-showcase/pull/330
