### ISSUE TITLE
Define layouts directly within `Activity` and `Fragment` constructors

### ISSUE THREAD

**Issue by igorwojda** [igorwojda/android-showcase#95]
We can simplify the project code
https://twitter.com/igorwojda/status/1245344121155395587

**Comment by sfeatherstone** [comment]
I'll take this

**Comment by igorwojda** [comment]
Thanks go for it 🙌

**Comment by sfeatherstone** [comment]
https://github.com/igorwojda/android-showcase/pull/111

**Comment by igorwojda** [comment]
Closed by
https://github.com/igorwojda/android-showcase/pull/111
